version: '3.8'

services:
  frontend:
    build: ./fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000

  backend:
    build: ./be
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./be:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    command: npm run dev
  

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydb

volumes:
  mongo-data:
