# Use an Alpine-based Node.js image
FROM node:20-alpine

# Install dependencies
RUN apk add --no-cache make g++ bash libc-dev libstdc++

# Set the working directory
WORKDIR /app

# Copy package files first (for caching layers)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the frontend source code
COPY . .

# Expose Next.js port
EXPOSE 3000

# Start Next.js app
CMD ["npm", "run", "dev"]
